In this code, first an input file is created with random values in a practical range and then that file is used to generate the schedule file.

In [ ]:
import pandas as pd
import datetime
import datetime as dt
import time
import numpy as np
import random

In [ ]:
def no_of_buses(n):
  bus_depart_time=[]
  if (n<=12): n=n
  else: n=12
  for j in range (0,n):
    m=n/12
    a=int(60/n)
    b=int(j*a/5)
    c=5*(b)
    bus_depart_time.append(c)
  return bus_depart_time

In [ ]:
print(no_of_buses(15))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]

In [ ]:
points=[]
n=int(input("Enter the no. of terminals: "))

for i in range (0,n):
  if (i==0):
    points.append("A")
  else:
    p=chr(ord(points[-1])+1)
    points.append(p)

print(points)

Enter the no. of terminals: 11
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K']

In [ ]:
print(dt.time(0+4))

04:00:00

In [ ]:
a=4
b=5
c=f'{a}-{b}'
print(type(c))
print(c)

<class 'str'>
4-5

In [ ]:
i=1
j=2
a=f'{dt.time(i+4)}-{dt.time(j+5)}'
print(a)

05:00:00-07:00:00

In [ ]:
freq=np.random.randint(10,size=19)
ghgf=[freq]
print(ghgf)
type(ghgf)
type(freq)

[array([1, 5, 1, 7, 7, 7, 2, 3, 7, 8, 2, 5, 2, 2, 4, 0, 8, 9, 4])]

numpy.ndarray

In [ ]:
l1=[]
for i in range (0,19):
  a=f'{dt.time(i+4)}-{dt.time(i+5)}'
  l1.append(a)
freq=np.random.randint(10,size=19)
freq2=freq.reshape(-1,1)
df001=pd.DataFrame([freq],index=range(1),columns=range(19))
df001.columns=l1
df001

,04:00:00-05:00:00,05:00:00-06:00:00,06:00:00-07:00:00,07:00:00-08:00:00,08:00:00-09:00:00,09:00:00-10:00:00,10:00:00-11:00:00,11:00:00-12:00:00,12:00:00-13:00:00,13:00:00-14:00:00,14:00:00-15:00:00,15:00:00-16:00:00,16:00:00-17:00:00,17:00:00-18:00:00,18:00:00-19:00:00,19:00:00-20:00:00,20:00:00-21:00:00,21:00:00-22:00:00,22:00:00-23:00:00
0,9,4,4,2,3,5,4,1,8,4,1,3,2,0,2,7,4,8,7

In [ ]:

hour1=np.random.randint(1,3)
min1=np.random.randint(60)
r_time=dt.time(hour1,min1)
print(r_time)

02:17:00

In [ ]:
df1=pd.DataFrame()
info_of_routes=[]
for j in range(0,n):
  for k in range(0,n):
    if(j!=k):

      freq=np.random.randint(10,size=19)
      hour1=np.random.randint(2)
      min1=np.random.randint(60)
      r_time=dt.time(hour1,min1)

      hour2=0
      min2=np.random.randint(30)
      b_time=dt.time(hour2,min2)

      r_id=100*(ord(points[j]))+10*(ord(points[k]))+ord((points[j]))-ord(points[k])

      l1=[]
      for i in range (0,19):
        a=f'{dt.time(i+4)}-{dt.time(i+5)}'
        l1.append(a)
      df001=pd.DataFrame([freq],index=range(1),columns=range(19))
      df001.columns=l1


      dict_of_route={
      "route_id":[r_id],
      "running_time":[r_time],
      "break_time":[b_time],
      "source":[points[j]],
      "destination":[points[k]],
      }

      info_of_routes.append(dict_of_route)
      df11=pd.DataFrame(dict_of_route)
      df11=pd.concat([df11,df001],axis=1)
      df1=pd.concat([df1,df11])
df1=df1.reset_index(drop=True)
df1

,route_id,running_time,break_time,source,destination,04:00:00-05:00:00,05:00:00-06:00:00,06:00:00-07:00:00,07:00:00-08:00:00,08:00:00-09:00:00,...,13:00:00-14:00:00,14:00:00-15:00:00,15:00:00-16:00:00,16:00:00-17:00:00,17:00:00-18:00:00,18:00:00-19:00:00,19:00:00-20:00:00,20:00:00-21:00:00,21:00:00-22:00:00,22:00:00-23:00:00
0,7159,01:50:00,00:03:00,A,B,2,4,3,4,8,...,9,4,0,4,5,0,8,8,7,2
1,7168,01:16:00,00:25:00,A,C,0,3,7,5,6,...,0,8,6,7,6,4,9,8,1,2
2,7177,01:49:00,00:09:00,A,D,9,5,0,7,6,...,7,7,8,8,6,6,3,6,5,5
3,7186,00:17:00,00:00:00,A,E,8,2,4,7,2,...,4,1,7,1,2,0,9,7,1,2
4,7195,00:12:00,00:14:00,A,F,2,7,2,9,5,...,9,3,1,0,3,5,4,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,8205,00:14:00,00:23:00,K,F,7,2,3,0,3,...,5,3,1,2,8,2,1,0,9,3
106,8214,01:32:00,00:05:00,K,G,4,9,5,7,0,...,5,4,5,7,7,2,8,0,8,3
107,8223,01:35:00,00:00:00,K,H,3,6,9,4,8,...,7,9,7,5,4,7,6,3,9,6
108,8232,01:51:00,00:11:00,K,I,2,2,8,8,2,...,9,0,5,7,3,6,9,9,3,2
109,8241,01:35:00,00:24:00,K,J,2,6,1,4,4,...,3,9,4,8,1,9,7,1,6,7

In [ ]:
def sour(point):
  f1_out=df1[(df1['source']==point)]
  f1_out=f1_out.reset_index(drop=True)
  return(f1_out)

In [ ]:
def min(a):
    return ((int(a[0:2])*60)+(int(a[3:5])))

In [ ]:
def no_of_buses(n):
  bus_depart_time=[]
  if (n<=12): n=n
  else: n=12
  for j in range (0,n):
    m=n/12
    a=int(60/n)
    b=int(j*a/5)
    c=5*(b)
    bus_depart_time.append(c)
  return bus_depart_time

In [ ]:
df201=pd.DataFrame()
total_n_initial=[100]
main_trip_arr=[0]
n_initial_pointwise=[]

running_bus=[]

for minute in range(240,1380,5):

  index=(int(minute/60)+1)

  for j in range (0,n):
    n_initial_at_point=[]
    df152=sour(points[j])

    for k in range (0 ,n):
      if j!=k:
        if df152['destination'].isin([points[k]]).any():

          start_place=points[j]
          end_place=points[k]

          row_index=df152.loc[df152['destination']==end_place].index[0]

          m=df152.iat[row_index,index]
          m=int(m)
          bus_depart_time=no_of_buses(m)

          if (minute - 60*(int (minute/60))) in bus_depart_time:

            for i in range (0,len(n_initial_pointwise)):
              if 'place' in n_initial_pointwise[i]:
                if (n_initial_pointwise[i]['place'][0]==points[j] and n_initial_pointwise[i]['ready_for_next'][0]<=minute):
                  n_initial_at_point.append(n_initial_pointwise[i]['id'][0])
                  n_initial_pointwise[i].clear()
                  break

            if (len(n_initial_at_point)==0):
              n_initial_at_point.append(total_n_initial[-1]+1)
              main_trip_arr.append(0)
              total_n_initial.append(n_initial_at_point[-1])

            curr_bus=n_initial_at_point[0]
            n_initial_at_point.pop(0)
            main_trip_arr[curr_bus-100]+=1

            r_t_dt=df152.iat[row_index,1]
            r_t=(str(r_t_dt))
            b_t_dt=df152.iat[row_index,2]
            b_t=str(b_t_dt)
            r_id=df152.iat[row_index,0]
            red_t=min(r_t)+min(b_t)+minute
            if (red_t>=1440):
              red_t=red_t-1440
            dict1={
            "id":[curr_bus],
            "trip_no":[main_trip_arr[(curr_bus-100)]],
            "route_id":[r_id],
            "source":[points[j]],
            "time_of_depart":[dt.time(int(minute/60),minute-(60*int(minute/60)))],
            "run_time":[r_t],
            "break":[b_t],
            "ready_for_next":[dt.time(int(red_t/60),red_t-(60*int(red_t/60)))],
            "destination":[points[k]]
            }

            running_bus.append(dict1)
            df202=pd.DataFrame(dict1)
            df201=pd.concat([df201,df202])

            awesome = [ minute - 4, minute -3, minute -2, minute -1, minute]

            for i in range (0,len(running_bus)):
              if 'destination' in running_bus[i]:
                if (running_bus[i]['destination'][0]==points[j]):
                  if (min(str(running_bus[i]['ready_for_next'][0]))) in awesome:
                    stored_id = running_bus[i]['id'][0]
                    curr_place= running_bus[i]['destination'][0]
                    reaching_time=running_bus[i]['ready_for_next'][0]

                    running_bus[i].clear()

                    dict2={
                    "id": [stored_id],
                    "place":[curr_place],
                    "ready_for_next":[min(str(reaching_time))]
                    }
                    n_initial_pointwise.append(dict2)


df201["index"]=list(np.arange(1,len(df201)+1))
df201

,id,trip_no,route_id,source,time_of_depart,run_time,break,ready_for_next,destination,index
0,101,1,7159,A,04:00:00,01:50:00,00:03:00,05:53:00,B,1
0,102,1,7177,A,04:00:00,01:49:00,00:09:00,05:58:00,D,2
0,103,1,7186,A,04:00:00,00:17:00,00:00:00,04:17:00,E,3
0,104,1,7195,A,04:00:00,00:12:00,00:14:00,04:26:00,F,4
0,105,1,7213,A,04:00:00,00:50:00,00:21:00,05:11:00,H,5
...,...,...,...,...,...,...,...,...,...,...
0,2077,2,7911,H,22:50:00,00:22:00,00:02:00,23:14:00,G,9292
0,1582,6,7967,I,22:50:00,00:08:00,00:21:00,23:19:00,B,9293
0,1799,3,7976,I,22:50:00,00:18:00,00:02:00,23:10:00,C,9294
0,1159,9,7994,I,22:50:00,01:27:00,00:05:00,00:22:00,E,9295
0,1818,4,8223,K,22:50:00,01:35:00,00:00:00,00:25:00,H,9296

In [ ]:
df201.to_csv('Schedule_Test.csv',index=False)